version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_admin
    ports:
      - "3306:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/db.sql:/db.sql